### ISSUE TITLE
32 bit version is broken

### ISSUE THREAD

**Issue by denizzzka** [denizzzka/dpq2#111]
https://github.com/denizzzka/dpq2/issues/109#issuecomment-390403140

**Comment by denizzzka** [comment]
fixed in #112

**Comment by Wulfklaue** [comment]
Can confirm, this fixes the 32bit builds.

**Comment by denizzzka** [comment]
can you also run integration tests?

**Comment by Wulfklaue** [comment]
Never done that before... I am currently manually testing.

Interesting is errors are now present on the final build:

libpq.dll ; 64bit
libpq.lib ; 64bit

```
object.Error@(0): Access Violation
----------------
0x02AF86CD
```

libpq.dll ; 32bit
libpq.lib ; 32bit

```
derelict.util.exception.SharedLibLoadException@AppData\Roaming\dub\packages\derelict-util-3.0.0-beta.2\derelict-util\source\derelict\util\sharedlib.d(158): Failed to load one or more shared libraries:
        libpq.dll - The specified module could not be found.
```

Its so much fun trying to get it working /s *lol* ...

**Comment by Wulfklaue** [comment]
The issue is that libpq needs a series of dlls to work.

Copy the official pq libs ( from the postgresql 10 Windows zip ) into SysWOW64 for the 32bit and system32 for the 64 bit. No dice ...

Copy the pqAdmin lib's next to the executable. Works

I get the feeling that the libs are not loaded correctly from the system path. Anyway, will look later at this. No time now to continue.

**Comment by denizzzka** [comment]
> I get the feeling that the libs are not loaded correctly from the system path.

Probably, this is related to DerelictPQ, not to dpq2
